name: Build and Release Native

on:
  push:
    paths:
      - "native/**"
      - ".github/workflows/native-release.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./native

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install GTK and WebKit2GTK dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository universe
          sudo apt-get update
          sudo apt-get install -y pkg-config libgtk-3-dev libwebkit2gtk-4.0-dev build-essential

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.25"

      - name: Get commit info
        id: commit
        run: |
          echo "SHA=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          echo "TIME=$(date -u +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT

      - name: Prepare
        run: |
          go mod tidy

      - name: Build Linux binary
        run: |
          GOOS=linux GOARCH=amd64 go build -o native-linux

      # - name: Build Windows binary
      #   run: |
      #     GOOS=windows GOARCH=amd64 go build -o native-windows.exe

      - name: Create native.version
        run: |
          echo "Commit: ${{ steps.commit.outputs.SHA }}" > native.version
          echo "Time: ${{ steps.commit.outputs.TIME }}" >> native.version
          ls -al

      - name: Create/Update Release with assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: native
          name: native
          draft: false
          prerelease: false
          files: |
            ./native/native-linux
            ./native/native.version
          overwrite_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
